### ISSUE TITLE
Update Copyrights to contain University of Stuttgart as Copyright Owner

### ISSUE THREAD

**Issue by lharzenetter** [OpenTOSCA/tosca-definitions-example-applications#3]
E.g., [here](https://github.com/OpenTOSCA/tosca-definitions-example-applications/blob/main/servicetemplates/http%253A%252F%252Fopentosca.org%252Fexample%252Fapplications%252Fservicetemplates/MyTinyToDo-MySql_Docker-w1/LICENSE#L190) must be replaced.

However, this should be done in ALL repos.

**Comment by lharzenetter** [comment]
```
      identification within third-party archives.

   Copyright [yyyy] [name of copyright owner]

   Licensed under the Apache License, Version 2.0 (the "License");
```

-->

```
      identification within third-party archives.

   Copyright 2021 University of Stuttgart

   Licensed under the Apache License, Version 2.0 (the "License");
```

**Comment by wederbn** [comment]
Seems to be solved and the Winery linked issue is independent, what do you think @lharzenetter ?

**Comment by lharzenetter** [comment]
Yes. However, I'm not quite sure whether new change have have been introduced that did not consider this change...
